"""
Abstract base class for LLM providers.

This module defines the interface that all LLM providers must implement,
enabling seamless switching between OpenAI (GPT-4) and local models (Ollama).
"""

from abc import ABC, abstractmethod
from collections.abc import Iterator
from dataclasses import dataclass


@dataclass
class LLMResponse:
    """Standardized response from LLM providers."""

    content: str
    model: str
    provider: str
    tokens_used: int | None = None
    latency_ms: float | None = None


class LLMProvider(ABC):
    """
    Abstract base class for LLM providers.

    All LLM implementations (OpenAI, Ollama, etc.) must inherit from this
    class and implement the required methods.
    """

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_prompt: str = "",
        temperature: float = 0.1,
        max_tokens: int = 2048,
        top_p: float | None = None,
    ) -> str:
        """
        Generate a response from the LLM.

        Args:
            prompt: The user prompt/query
            system_prompt: Optional system prompt for context/persona
            temperature: Sampling temperature (0.0 = deterministic)
            max_tokens: Maximum tokens in response
            top_p: Nucleus sampling probability cutoff. When set, only the
                smallest set of tokens whose cumulative probability exceeds
                top_p are considered. Use either top_p or temperature, not
                both simultaneously.

        Returns:
            Generated text response
        """
        pass

    @abstractmethod
    def generate_with_metadata(
        self,
        prompt: str,
        system_prompt: str = "",
        temperature: float = 0.1,
        max_tokens: int = 2048,
        top_p: float | None = None,
    ) -> LLMResponse:
        """
        Generate a response with metadata (tokens, latency, etc.).

        Args:
            prompt: The user prompt/query
            system_prompt: Optional system prompt for context/persona
            temperature: Sampling temperature
            max_tokens: Maximum tokens in response
            top_p: Nucleus sampling probability cutoff (see generate()).

        Returns:
            LLMResponse with content and metadata
        """
        pass

    @abstractmethod
    def generate_stream(
        self,
        prompt: str,
        system_prompt: str = "",
        temperature: float = 0.1,
        max_tokens: int = 2048,
        top_p: float | None = None,
    ) -> Iterator[str]:
        """
        Stream a response token-by-token from the LLM.

        Args:
            prompt: The user prompt/query
            system_prompt: Optional system prompt for context/persona
            temperature: Sampling temperature
            max_tokens: Maximum tokens in response
            top_p: Nucleus sampling probability cutoff (see generate()).

        Yields:
            Text chunks as they are generated by the model
        """
        pass

    @abstractmethod
    def get_model_info(self) -> dict:
        """
        Get information about the current model.

        Returns:
            Dict with keys: provider, model, local, context_window
        """
        pass

    @abstractmethod
    def is_available(self) -> bool:
        """
        Check if the provider is available and configured.

        Returns:
            True if provider can be used, False otherwise
        """
        pass

    @property
    @abstractmethod
    def supports_vision(self) -> bool:
        """Whether this provider/model supports image inputs."""
        pass
